
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: <role-binding-name>
  namespace: <target-ns>
roleRef:
  apiGroup: rbac.authorization.k8s.io  
  kind: Role
  name: <role-name>
subjects:
- kind: ServiceAccount
  name: <application-controller-name> 
  namespace: <application-controller-namespace> 
